### PR TITLE
A user friendly semanticHomeMenu_Simple24hTimepicker

### PR DESCRIPTION
**Pull request by G-Ork**
Just initialize the items on the fly if pushing the spinner buttons.

### CODE REVIEW

**Comment by G-Ork** [comment]
I have extended the examples in markdown. Also fixed the seconds in timestamp if item is null. So all roller roll almost at the same time.

**Comment by hmerk** [comment]
> I have extended the examples in markdown. Also fixed the seconds in timestamp if item is null. So all roller roll almost at the same time.

I am unsure to approve your changes. We did not add binding specific entries in the documentation by intention. You now added KNX examples, which will not apply to all users.
Furthermore, the timepicker widget is not part of this project and I don‘t really want it to become part of it, even with your modification. Hence we woul need to support code which was not written by us originally.
You‘d better sugggest your initialization enhancement to the original widget on the marketplace.

**Comment by G-Ork** [comment]
It would no problem to replace the knx binding with a placeholder.  The documentation is bare and just on a level for someone who is able to figure out by themself. Its a time killer for someone stepping in. 

I thought it would be a better to include the widget so the user do not has configure it. 
But i guess the is no user concept in openhab  :smiling_face_with_tear:

**Comment by hmerk** [comment]
Wow, especially your last sentence is embarrassing.
This is absolutely wrong. We have done a lot to improve user experience in the last year.
Rejecting your changes to be included in this UI project is a complete different story and I will explain why.
First of all, you need to understand the marketplace rules, which say that there should not be two versions of the same widget. So the better and more user friendly way would be to propose your improvements to the original timepicker widget on the marketplace. This way all users using it would benefit, not just the semanticHomeMenu users.
Furthermore, only one widget needs maintenance and not two of the same kind.

Regarding the documentation, there are no channel examples on purpose, as those are different between the bindings. Having those added might irritate users more than helping them. Additionally, you can add the items with our examples snd then simply use the UI linking feature to complete the setup. Quite easy.

For the future, I am already investigating ways to make the complete setup easier, mostly "single step" but this is a very long road to go....

**Pull request closed without merging**
